
on: [push, pull_request]

name: save-to-dropbox

jobs:
  save-to-dropbox:
    runs-on: macOS-latest
    steps:
      - uses: deka0106/upload-to-dropbox@v1
      with:
        dropbox_access_token: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
        file: test.txt
        path: test.txt
